[tool.poetry]
name = "cloudsend"
version = "0.5.6"
description = "CloudSend is a Python package that allows you to run any script on a cloud service (for now AWS only)."
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/benbenz/cloudsend"

[tool.poetry.dependencies]
python = "^3.9"
bcrypt = "3.1.5"
cryptography =  "3.1.1"
protobuf = "^3.20"
boto3 = "1.23.10"
jcs = "^0.2"
pyyaml = "^6.0"
asyncssh = "~2.12.0"
ortools = "9.0.9048"
scriptflow = {version = "^0.2.5", optional = true}

[tool.poetry.extras]
scriptflow = ["scriptflow"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
demo = 'cloudsend.app:main'

[tool.pytest.ini_options]
asyncio_mode="strict"
testpaths = [
    "tests"
]
